### ISSUE TITLE
Update and expand User Manual

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio_docs#5]
I would like to contribute to your project.  I propose to initiate by updating and adding details to the User Manual.  I thought it would be best to check in first and see if I you have any needs or priorities that I can service thru contribution.

**Comment by edwinvandeven** [comment]
As you've started working on it, I'll close this issue

**Comment by NerdsLogic** [comment]
My only feedback at closure is to assign the issue to communicate custody of effort or commitment to contributing to said issue.  Could this be called a project?
